# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f82c6157de51524fa9b2d921ad1444eb612d84ad6b0890b4645ecf24eb492b32e904177e0ecb6c2249856a98d546dfa9f26fa4912d6dc0d12d56f6a81a2bfc0b

test:
  secret_key_base: 8f216985b0f94a057e19b8cc02736b6c2871bb50f306d8512bb25db2b75e49f29318f62d51675c6eb4129168677fb5ac11308a074a68816728a0edc011ae1aa6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
